tasks:
  - name: Install Hugo, init submodules and start website
    init: |
      curl -LO https://github.com/gohugoio/hugo/releases/download/v0.101.0/hugo_extended_0.101.0_Linux-64bit.deb && \
      sudo dpkg -i hugo_extended_0.101.0_Linux-64bit.deb && \
      sudo rm hugo_extended_0.101.0_Linux-64bit.deb
      git submodule update --init --recursive
    command: |
      cd website_and_docs
      hugo server --baseUrl $(gp url 1313) --appendPort=false

# List the ports you want to expose and what to do when they are served. See https://www.gitpod.io/docs/config-ports/
ports:
  - port: 1313
    onOpen: open-preview
